name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: mvn clean package -DskipTests

      - name: Tests
        run: mvn test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helloWorld-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env -u)
          docker build -t hello-world:${{ github.sha }} .

      - name: Update Deployment Image
        run: |
          docker config use-context docker-desktop
          kubectl set image deployment/hello-world \
            hello-world=hello-world:${{ github.sha }}

      - name: Wait For Rollout
        run: |
          kubectl rollout status deployment/hello-world
